## Platform = {android, ios, browser_stack}
Platform=android

# Grid Specific
AppiumServer=http://127.0.0.1:4723/wd/hub

# Test Data Specific
TCIDColumn=TC_ID
RunmodeColumn=RunMode
#TestDataExcelFileName=TestDataSelendroid.xlsx
TestDataExcelFileName=WhereIsMyTrain.xlsx
#Both these variables are required for Selendroid tests
#RunModeSheetName=Registration
#TestDataSheetName=Reg
RunModeSheetName=Sheet1

# App Info for Local Android
#AppName=TestApp.apk
#AppName=Where is my Train.apk
AppName=maauka.apk

AutomationName=uiautomator2
#DeviceName=M2003J6B1l

#Ronak
DeviceName=RMX2151

#DeviceName=Nexus_5X
#UDID=8fc3ecc0

#Ronak
UDID=7X85NJYDMRLJAYZH

#UDID=86bf1ba7s
#UDID=emulator-5554
PlatformVersion=12
#PlatformVersion=11.0
#AppPackage=com.paytm.paytmplay
#AppPackage=io.selendroid.testapp
#AppPackage=com.whereismytrain.android
AppPackage=com.stardreamcruises.app
#AppActivity=com.gamepind.login.ui.LoginActivity
#AppActivity=io.selendroid.testapp.HomeScreenActivity
#AppActivity=com.whereismytrain.view.activities.HomeActivity
AppActivity=com.stardreamcruises.app.MainActivity
ignoreHiddenApiPolicyError=true

NoReset=true
AutoGrantPermissions=true

# App Info for Local iOS

# App Info for BrowserStack/ Cloud
CloudDeviceName=Google Nexus 6
CloudPlatformVersion=6.0


# General Settings
#In Ms
Timeout=3000

# Credentials
UserName=
Password=

#Extent Report
Environment=Staging
TeamName=Test team

# BrowserStack Credentials
bsUserName=
bsAccessKey=
bsAppHash=